language: cpp
os:
  - linux
compiler:
  - gcc
branches:
  only:
  - master
env:
  global:
    - COMPILER=g++-7

script:
  - cd $TRAVIS_BUILD_DIR/ECSTools   
  - make 
  - ls 
  - ./$TRAVIS_BUILD_DIR/ECSTools/ECSTools
  - cd $TRAVIS_BUILD_DIR/Test
  - make
  - ./TRAVIS_BUILD_DIR/Test/ESCTest
